<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kegiatan</name>
   <tag></tag>
   <elementGuidId>835eace9-b041-4d2a-a10c-1ebacd896163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;kegiatan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='kegiatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eed829cb-77cd-4232-8df7-8037b311b020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2719639c-837a-4992-bcb0-7541f7bb2a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>e96f4848-27bb-4622-b712-972a48b7dda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kegiatan</value>
      <webElementGuid>9396bd39-5f3d-4928-a283-89e733ec635c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat</value>
      <webElementGuid>65d3b06e-039d-455b-8312-16093ec5640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[4]/div[@class=&quot;modal overflow-auto fade show d-block&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5a525fa4-d455-4623-b551-2f5af46c6dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='kegiatan']</value>
      <webElementGuid>f129d75a-cd87-4f57-8c0e-0c73d33e9a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[8]/div[2]/div/select</value>
      <webElementGuid>9cca19e0-cbee-435a-97f8-3d55a4ed6b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[1]/following::select[1]</value>
      <webElementGuid>36a84082-fea7-4e99-9117-395bb4c04e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Case'])[1]/following::select[1]</value>
      <webElementGuid>c6998451-426d-4ead-9291-c70fe0dba30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil'])[1]/preceding::select[1]</value>
      <webElementGuid>f6ffdc22-9003-4b29-bfcb-c7d6d7cd0c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jam Efektif'])[1]/preceding::select[1]</value>
      <webElementGuid>e9de71e9-4f99-4c8a-b0ae-bede308c0a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/select</value>
      <webElementGuid>7dcc1dcb-2434-42f9-b825-8fa483e5c275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'kegiatan' and (text() = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat' or . = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat')]</value>
      <webElementGuid>42f886ea-8fca-469c-bc22-6923f8acab3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
