<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ModeKerja</name>
   <tag></tag>
   <elementGuidId>4736de5a-57a6-40af-816d-d6cef7297afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='mode_kerja']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;kegiatan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>625ee91b-9e74-4ff8-ba78-e6d7756722e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>57354d24-746e-4c7d-a7ae-6a7764b53c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>2e21bf07-3d63-483c-9740-224f68c2508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kegiatan</value>
      <webElementGuid>57f4ae93-03db-4bc4-8b8a-2f555fd5df47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat</value>
      <webElementGuid>d53e1b52-a6d5-4615-b2c4-888253d74877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[4]/div[@class=&quot;modal overflow-auto fade show d-block&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>97e76ee7-ccab-433f-b521-8a05c8d6eede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='mode_kerja']</value>
      <webElementGuid>b76eaf6c-8a24-49e1-8a70-aa024e7a8979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[8]/div[2]/div/select</value>
      <webElementGuid>e9257425-5f5f-4c0a-915d-ce39a4748cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[1]/following::select[1]</value>
      <webElementGuid>6ac34b44-c9d7-42cd-9529-0ec29d1fd316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Case'])[1]/following::select[1]</value>
      <webElementGuid>9367c964-0ae8-42a7-bd95-6997647767d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil'])[1]/preceding::select[1]</value>
      <webElementGuid>01e77bed-1bff-4920-b35a-5af78c613f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capaian'])[1]/preceding::select[1]</value>
      <webElementGuid>3a6ec91f-08cf-4757-b351-c3e74fef5c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/select</value>
      <webElementGuid>8cd8ec97-9efd-4ab1-b3cc-fa3635512122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'kegiatan' and (text() = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat' or . = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat')]</value>
      <webElementGuid>68e3fd90-5a72-407a-97e4-fdb32d90f2d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
