<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SideBarToggle</name>
   <tag></tag>
   <elementGuidId>a1347cf5-4efe-4e8f-94c2-3b89251cb6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.c-header-toggler-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/header/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56f8972a-718a-4165-be1d-37004d1ca124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-header-toggler-icon</value>
      <webElementGuid>f3e0d8b1-a37c-4958-ba48-352b529b72d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/header[@class=&quot;header-root c-header c-header-light c-header-fixed&quot;]/button[@class=&quot;c-header-toggler ml-md-3 d-lg-none&quot;]/span[@class=&quot;c-header-toggler-icon&quot;]</value>
      <webElementGuid>059576fb-5e29-4b81-9b20-9099f36df42d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/header/button/span</value>
      <webElementGuid>0e78f629-52bf-4f06-bf2f-c73509c08b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>a2c6bb4d-e9d3-4733-b56f-4c8674b81d79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
