<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_UserProfile</name>
   <tag></tag>
   <elementGuidId>0f2e80d3-74d2-4d41-b696-5c2da716637b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c-header-nav-link.nav-link > div.c-avatar > img.c-avatar-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/header/ul[3]/li/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7dffb36c-8aa7-45ab-a463-ca2de8d2a85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-avatar-img</value>
      <webElementGuid>f6671f4f-86fa-4ff4-87fe-4ba541a6ad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png</value>
      <webElementGuid>950044f8-0c02-4d2f-8c3e-f7566e76f465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>admin@bootstrapmaster.com</value>
      <webElementGuid>f4e57068-cac6-4727-930b-c8142cf18632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/header[@class=&quot;header-root c-header c-header-light c-header-fixed&quot;]/ul[@class=&quot;px-3 c-header-nav&quot;]/li[@class=&quot;c-header-nav-items mx-2 dropdown nav-item&quot;]/a[@class=&quot;c-header-nav-link nav-link&quot;]/div[@class=&quot;c-avatar&quot;]/img[@class=&quot;c-avatar-img&quot;]</value>
      <webElementGuid>593bac04-9107-4ef5-bbc2-6bec13fbdd94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/header/ul[3]/li/a/div/img</value>
      <webElementGuid>56969a8d-fd4f-4018-bf0f-6289daa8a374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='admin@bootstrapmaster.com'])[2]</value>
      <webElementGuid>89adedcd-525b-41d3-b182-fef1cc2a70e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>832195d2-c887-4ce0-881c-104bcbeb7ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png' and @alt = 'admin@bootstrapmaster.com']</value>
      <webElementGuid>619de1ec-5fe1-4862-afab-d465261c0ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
